version: '3'
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=password
      - DB_HOST=wordpress-db
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
  wordpress-db:
    image: mysql:8.0.28-oracle
    volumes:
      - ./dump/:/docker-entrypoint-initdb.d/
      - wordpress-db-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin02"
    links:
      - wordpress-db
    ports:
      - 9991:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: wordpress-db
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  wordpress-db-data:
    driver: local
